### ISSUE TITLE
coman-no-forearm has arms!

### ISSUE THREAD

**Issue by Pouya-moh** [corlab/cogimon-gazebo-models#7]
Hi.
I am a bit unfamiliar with this format so there is a good chance that I might be wrong. With that said:
`urdf` and `srdf` files in [iit-coman-no-forearms](https://github.com/corlab/cogimon-gazebo-models/tree/master/iit-coman-no-forearms) are bringing up coman _with_ the forearm. To be sure, I spawned the `model.urdf` outside of our framework via `ros` and it brings the correct model with no forearm. Which tells, either there is something hardcoded somewhere, a problem is srdf or probably I am making a mistake. Relevant part of my ops files:

```
var string model_name = "model://iit-coman"
var string path_model_urdf = os.getenv("GAZEBO_MODEL_PATH")+"/iit-coman-no-forearms/model.urdf"
var string path_model_srdf = os.getenv("GAZEBO_MODEL_PATH")+"/iit-coman-no-forearms/coman_no_forearms.srdf"

gazebo.spawn_model("coman", model_name, 10)
robot_gazebo.getModel("coman")

robot_gazebo.loadURDFAndSRDF(path_model_urdf, path_model_srdf)
```

any ideas?

EDIT:
found the issue, never mind.

**Comment by Pouya-moh** [comment]
Turned out I am a complete moron :|

**Comment by EnricoMingo** [comment]
Model_name is wrong

Il 04 Gen 2017 17:40, "Pouya" <notifications@github.com> ha scritto:
